spring:
  application:
    name: Marvel
  data:
    mongodb:
      host: ${MONGO_DB_HOST}
      port: ${MONGO_DB_PORT}
      database: ${MONGO_DB_DATABASE}
#      username: ${MONGO_DB_USERNAME}
#      password: ${MONGO_DB_PASSWORD}
server:
  port: 8080
  http2:
    enabled: true
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always
    include-stacktrace: always
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger.html
logging:
  level:
    root: info
    org.springframework.web: off
